### ISSUE TITLE
Missing AdformTrackingSdk class for Android

### ISSUE THREAD

**Issue by jmyrland** [adform/adform-tracking-sdk-xamarin#3]
Hi,

I cant seem to find the class `AdformTrackingSdk` as described in the README. What namespace is this class part of?

I can see the `Com.Adform.Adformtrackingsdk`namespace, but it does not contain the class `AdformTrackingSdk`.

![screen shot 2016-11-28 at 12 09 12](https://cloud.githubusercontent.com/assets/837651/20666233/810653d8-b563-11e6-990f-3a5541b287da.png)

![screen shot 2016-11-28 at 12 07 21](https://cloud.githubusercontent.com/assets/837651/20666181/4986fc78-b563-11e6-92cd-e6e8bbe53a03.png)

**Comment by rprunskas** [comment]
You should find "AdformTrackingSdk" in Com.Adform.Adformtrackingsdk namespace. You could import like this:

using Com.Adform.Adformtrackingsdk;

Have you added AdformTrackingBindingAndroid as a reference in your project?

**Comment by jmyrland** [comment]
> Have you added AdformTrackingBindingAndroid as a reference in your project?

Of course. I'm guessing if I didn't, I would not have gotten the `Com.Adform` namespace (as seen in the attached images).

I'm guessing it has something to do with the target framework of the project. It's defaulted to "latest version" which is 7.0 (Nougat). I'll try changing this property and see what happens. I'll let you know of my results shortly.

**Comment by jmyrland** [comment]
I changed the target version for the `AdformTrackingBindingAndroid` project to 6.0 (Marshmallow). By doing this, the `AdformTrackingSdk` becomes available. I'm assuming this resolves the issue.

Is there any way to verify that the SDK is integrated? I can't seem to see anything in the logs.

**Comment by rprunskas** [comment]
You could check if tracking events are coming in Adform web platform. 

Sorry for the late reply.
