### ISSUE TITLE
Problem with add reference to project

### ISSUE THREAD

**Issue by caezon** [adform/adform-tracking-sdk-xamarin#4]
Hi,

I add Adform Tracking SDK biddings (android) to my project and everything work fine, but when add  a reference to Adform Tracking SDK biddings  in my project, generate errors.

![captura de pantalla 2018-06-14 a la s 11 05 55](https://user-images.githubusercontent.com/19320514/41434326-5ac0edb8-6fe9-11e8-99ba-498195dfec03.png)

**Comment by rprunskas** [comment]
Please try to increase Java max heap size:

https://stackoverflow.com/questions/36835790/getting-outofmemoryexception-in-xamarin
